### ISSUE TITLE
Tab for Colony's Buildings in the Town Hall UI

### ISSUE THREAD

**Issue by Dryelo** [ldtteam/minecolonies-features#228] opened 2020-12-24 23:19 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- Forge v35.1.13
- MineColonies Version: minecolonies-0.13.437-RELEASE

## Is your feature request related to a problem?
Once your colony starts getting bigger, it gets harder to remember which building needs an upgrade.
Find a way to get an overview which building in your colony is which level

## Feature description
I'd like a tab in the Town Hall UI with a list of the colony's buildings (similar to the tab with the citizens).
Once you click on a building, you'd be able to see:
- the building's hut location (X,Y,Z)
- the building's level (bonus feature: an indicator if the building is in the queue for an upgrade)
- the number of assigned workers (bonus feature: the names of the worker(s))

### Notes or related things
Of the three items mentioned above, the second one is most important for me.
If there's a better / easier way to achieve this, that would be fine, too. Perhaps a special tool that illuminates the building's outline in different colors)

Great mod, btw, keep it up!

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-12-25 03:46
Duplicate of #209, which is planned. Btw you're on 437 release, we recommend updating to the latest alpha (536 last I checked). All our classifications are equally as stable, and we only push out releases/betas because Curseforge demands it.

**Closed by ravenbuilder934** 2020-12-25 03:46 UTC
Labels: Feature: Request

**Comment by Dryelo** [comment] 2020-12-27 14:57
didn't see that post, sorry.
But glad to hear it's planned :)
