### ISSUE TITLE
Add a marriage system

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#43] opened 2020-07-25 14:56 UTC
# Prerequisites

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**
- [X] This is a feature request issue and not a bug report. Please create all bug reports [here](https://github.com/ldtteam/minecolonies/issues).

### Context

- Minecraft Version: 1.15.x

### Expected behavior

>I realized Minecolonies doesn't have a marriage system, which would be very fitting with Minecolonies in my opinion. You would have to get a church built in your colony first, before you can get married using the Minecolonies mod, and to get divorced you will have to go to the town hall to do so. Marriage to someone includes special features, such as being able to receive gifts from your husband or wife.

#### Specifications

*

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-07-28 18:49
I posted my own take on this in a comment of the Planned and Requested Features issue:

> Citizens would randomly marry each other at a church (chapel?), and a priest would marry them. The wedding would take the whole Minecraft day, and all citizens would come to watch. The citizens that watched would get a temporary happiness buff, and the newly married ones would get a big buff on the day of the wedding and a smaller buff for every day they're married afterward. A citizen can only be married to one other citizen at a time, and there would be no gay or lesbian marriages (because this is colonial times). There would also be divorces, at the Town Hall. The likelihood of citizens getting a divorce would be based on the citizens' Adaptability skill. Only the citizens getting divorced would come to the TH, and they would have a temporary happiness debuff afterward. Citizens rarely have kids if they're not married to each other, and if they do, the kid has lower skills and a permanent happiness debuff. The mom would also have the happiness debuff. (https://discord.com/channels/139070364159311872/240841248750043137/724211190284419073)

**Comment by ravenbuilder934** [comment] 2020-09-24 14:23
Duplicate of #128?

**Comment by ShadowProtocol** [comment] 2020-09-25 04:01
Hmm, seeing as # 128 is a combined issue, it might be better to cancel it as the duplicate and go with the individual ones

**Comment by ravenbuilder934** [comment] 2020-09-25 15:22
In my opinion #128 is more thought-out and has more points.

**Comment by EliotWL** [comment] 2021-02-19 06:29
> A citizen can only be married to one other citizen at a time, and there would be no gay or lesbian marriages (because this is colonial times).

Could possibly be a config option for this or maybe a colony by colony setting.  Would allow each colony to have a bit of a difference beyond aesthetic?  (while also not completely excluding the lgbt for the sake of minor realism)

**Comment by Mewcenary** [comment] 2021-07-10 17:52
@idtteam
@ravenbuilder934
I'd like to add to this, the ability to marry a colonist and have your own family as well, plus titles, such as a Lord/Lady or King/Queen to govern over your colony; Your spouse could help with easy tasks requests too.

**Comment by Thodor12** [comment] 2022-07-09 21:23
Marriage is currently not going to happen anymore, we do have the families system though

**Closed by Thodor12** 2022-07-09 21:23 UTC
Labels: Feature: Request
