### ISSUE TITLE
Late game guards (ride horses).

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies-features#293] opened 2021-02-14 01:27 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.610-ALPHA-universal

## Is your feature request related to a problem?

Nop.

## Feature description

The feature involves one more Hut, in this case a Horse hut (stable Hut's) and only can be build after a research on University. And more, you can unlock 'Riders', to allow the guards colony to use horses.
The guards only use the horses during RAIDs (or the entire time).

It's just an idea that I had. This can be a new way to made minecolonies more immersive.

### Notes or related things

1. One more Hut (to create horses), and other to be a stable.
2. Two or more Research to unlock full potential
3. More challenge during RAIDs.
4. More fun.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2021-02-14 02:18
Duplicate of #61 (post a comment there)

**Closed as completed by ravenbuilder934** 2021-02-14 02:18 UTC
Labels: Feature: Request
