### ISSUE TITLE
[1.16.5 request] Merge items

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies-features#597] opened 2021-12-14 03:32 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: not nessisary
- Related Mods and their Versions: also not nessisary

## Is your feature request related to a problem?

Inventory space is valuable, so why not make some merge items to save some space

The Resourceful Clipboard: Forge by Merging a Clipboard and a Resource builders list (like this new thing btw) in a smitthing table, will serve as both functions of a clipboard and a resource document

upgrade it with materials to upgrade its capacity for the resource section (allows for you to go about though different materials being requested by specific building huts via a toggle list; progresses though iron-gold-diamond-emerald- and if necessary (and for bragging rights if any) netherite

the Multipurpose Structure tool: combines the shape tool and the structure tool, works as both, right click while holding shift to toggle between shape and build mode (Will also automatically switch into build mode if its in shape mode and a building needs to be built with its layout planning

## Enhancement or Change description
already explained above

### Notes or related things
on an unrlated note, an upgrade for the storage center to allow for mailboxes to have a toggle on only showing what items are in its storage when checked or toggled would be nice to see what you actually have

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shibva** [comment] 2021-12-14 03:37
addionaly the resourseful clipboard can also recive upgrades form research done by the univesity, allowing for addional features to be unlocked, but will need certain other buildings present to take effect

this can make it the ULTIMATE tool for your colonly, check items, request, and even summon your guards with an upgraded clipbord though your research!

**Comment by Shibva** [comment] 2021-12-14 04:09
example recipie to make the Resourceful Clipboard
![image](https://user-images.githubusercontent.com/38770780/145931567-8f97e4e7-0a77-484e-a318-1318f1a24f91.png)

**Comment by Thodor12** [comment] 2022-07-09 22:08
Already covered in #326
Duplicate of #326

**Closed as not planned by Thodor12** 2022-07-09 22:08 UTC
Labels: Enhancement / Change Request
