### ISSUE TITLE
Anti-waypoints

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies-features#99] opened 2020-07-29 20:55 UTC
Suggestion from Discord

### Expected behavior

- Waypoints that mark places for the colonists to avoid when pathfinding
- https://discord.com/channels/139070364159311872/240841248750043137/409248932686725121

#### Specifications
- May work in a radius around the anti-waypoint, or form rectangles from point to point

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by ShadowProtocol** [comment] 2020-08-07 13:38
Essentially a duplicate of #42

**Closed by ShadowProtocol** 2020-08-07 13:38 UTC
Labels: duplicate, feature request
