### ISSUE TITLE
Courier prioritization toggle

### ISSUE THREAD

**Issue by EliotWL** [ldtteam/minecolonies-features#317] opened 2021-03-11 03:58 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.690-ALPHA-universal.jar

## Is your feature request related to a problem?
Rare issue but sometimes I find myself being annoyed about how the request system is prioritizing things between pickups and drop offs.  Usually the issue stems from the courier(s) wanting to pick up everything before they drop things off a lot of the time which is likely just something what time the request came up.

## Feature description

- Courier huts to have a toggle button to switch between prioritizing pick up or drop off or standard.  
-      Basically have it so for each courier, you could fine tune which they prioritize.  Picking things up, or dropping things off, or just following the regular scheduler.  

### Notes or related things
You guys are great and I love the mod!  I just am really tired of my builders taking 4 days to build a small building just because every producer hut has something to pick up super often.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment] 2022-07-10 16:56
The root cause of this is just a "bad" implementation of the AI, this doesn't need a specific prioritization support, that will only complicate the system even more and most likely turn into even less efficient working.

Going to close this in favor of #542

**Closed as completed by Thodor12** 2022-07-10 16:56 UTC
Labels: Feature: Request
