### ISSUE TITLE
Allow postbox to request items continuously.

### ISSUE THREAD

**Issue by beringtom** [ldtteam/minecolonies-features#197] opened 2020-11-16 07:10 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.x
- MineColonies Version: 0.13.450 Alpha
- Related Mods and their Versions:

## Is your feature request related to a problem?

No.

## Enhancement or Change description

Change the postbox to allow an item to be requested continuously.

### Notes or related things

Usecase: 
Other mods can then get items from the minecolonies warehouse without being piped directly from the warehouse block.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-11-16 14:49
Duplicate of #97

**Comment by beringtom** [comment] 2020-11-16 16:24
Closed as a duplicate!

**Closed** 2020-11-16 16:24 UTC
Labels: Enhancement / Change Request
