### ISSUE TITLE
Builder : keep in stock

### ISSUE THREAD

**Issue by AndMattBurt** [ldtteam/minecolonies-features#147] opened 2020-09-02 17:19 UTC
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1:14:4 but cannot see it in latest (1:16:2) either
- MineColonies Version: 0.10.715

## Is your feature request related to a problem?

Having to wait for the builder to receive torches from warehouse at the end of every build.
## Feature description

Could set items to always keep stocked in the inventory e.g. stack of torches, 20 oak stairs etc.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2020-09-02 17:22
This already exists in the warehouse and restaurant. 0.10.715 is a *very* old version, please update to 0.13.210 (for 1.15.2)!

**Comment by AndMattBurt** [comment] 2020-09-02 17:39
I am aware it's an old version but I did have a look in the newer ones, how do you access the warehouse stock feature?

**Comment by ravenbuilder934** [comment] 2020-09-02 17:40
It's on the 3rd page of the warehouse GUI

**Comment by AndMattBurt** [comment] 2020-09-02 17:50
Cool, I see that which is super neat, but that could that be implemented for all the professionals (builder as a priority)?
So the builder doesn't have to keep waiting for the delivery every time?

**Comment by ravenbuilder934** [comment] 2020-09-02 18:25
Probably could. Edit the body of this issue to reflect that and the devs might add it.

**Comment by ravenbuilder934** [comment] 2020-09-24 14:42
Duplicate of #14

**Comment by Thodor12** [comment] 2022-07-09 21:44
Builder

**Closed by Thodor12** 2022-07-09 21:44 UTC
Labels: Feature: Request
