### ISSUE TITLE
Hunter Hut

### ISSUE THREAD

**Issue by PmanAce** [ldtteam/minecolonies-features#519] opened 2021-08-12 03:43 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version:
- MineColonies Version:

## Is your feature request related to a problem?

My colony is overrun by sheep, pigs and chickens that spawn or escape their huts. 

## Feature description

Having a new hunter hut would benefit a colony in several ways. Great way to deal with passive spawns overcrowding the colony. Extra source of food and drops too. 

Could also allow hunting aggressive mobs during the night for example. 

### Notes or related things

Good way to employ citizens that don't have jobs, can support many hunters at a time. 
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment] 2022-07-09 22:15
Duplicate of #519

**Closed as not planned by Thodor12** 2022-07-09 22:15 UTC
Labels: Feature: Request
