### ISSUE TITLE
#Guard4Builder

### ISSUE THREAD

**Issue by YouKnowWhoRight** [ldtteam/minecolonies-features#702] opened 2022-07-15 11:50 UTC
### Prerequisites 

- [Not Sure] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.764-ALPHA

## Is your feature request related to a problem?
I'm always frustrated when there is a message stated that my builder died while building because of hostile mobs which spawns because the building for example University is dark enough. I tried putting torches inside the buildings but my builders always break it before continue doing their work and three of my builders died just for one single building and I can't be there all the time to protect them since I am more things to do far away.

## Feature description

Builder should also be able to have guard just same as miner who should always follow the builder to anywhere the builder go and protect him. Specifically, the guard should attack any HOSTILE mobs that is within a certain amount of block like a 4 or 8 blocks area.

### Notes or related things
None
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment] 2022-07-15 11:56
I think the quarrier could benefit from this also.  My thoughts are the guard is in 'follow' mode of the worker and attacks any mob that comes within a prescribed range.

**Comment by Thodor12** [comment] 2022-07-15 11:58
Duplicate of #80

**Comment by Thodor12** [comment] 2022-07-15 11:59
Please add discussion onto the mentioned issue

**Closed as not planned by Thodor12** 2022-07-15 11:58 UTC
Labels: Feature: Request

**Comment by YouKnowWhoRight** [comment] 2022-07-15 13:01
> 

what this mean?

**Comment by YouKnowWhoRight** [comment] 2022-07-15 13:03
> Duplicate of #80

oh, There is another one 620 chapter before me. I didnt notice that... we are different anyways since I am only asking for builder but I am very sorry. Are you guys planning on adding this? Or did you add it? Because I didnt see it in my game.

**Comment by Thodor12** [comment] 2022-07-15 13:09
Nothing in the features is up for consideration until the devs greenlight something from here

**Comment by Thodor12** [comment] 2022-07-15 13:10
You are always free to pick it yourself if you know how to code, but always ask one of the lead devs if you want to pick something up and ask them first if this is even wanted behaviour
