### ISSUE TITLE
Powder Snow deaths.

### ISSUE THREAD

**Issue by Jolito61** [ldtteam/minecolonies-features#615] opened 2022-01-28 15:58 UTC
### Prerequisites 

- [ Yes] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ Yes] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [Yes ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.374-ALPHA

## Is your feature request related to a problem?

Yeah, Villagers don't know how to evade powder snow. And they die a lot, Making your village virtually useless, first. Couriers die. A lot, and the other citizens don't have time to process how many deaths there are, and cease working.
## Feature description

Instead of making them completely evade it. We can make a university investigation in the technology section. (That isn't a master investigation, so that everyone can have it) where citizens are made immune to freezing, and are able to walk inside of it. We can even expand it and make guards and soldiers hide in snow, to do ambushes.
### Notes or related things

Please don't put the investigation too late in the technology tree, since if the researchers are constantly dying due to freeze, They can't really do anything about it.
---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment] 2022-07-09 21:08
Duplicate of #611

**Closed as not planned by Thodor12** 2022-07-09 21:08 UTC
Labels: Feature: Request
