### ISSUE TITLE
can you create an 8 bit minecolonies voicepack?

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ldtteam/minecolonies-features#794] opened 2023-10-30 13:19 UTC

**Comment by Thodor12** [comment] 2023-10-31 08:58
duplicate of #795

**Closed as not planned by Thodor12** 2023-10-31 08:58 UTC
Labels: Feature: Request

**Comment by SonicTheHedgehog58987276** [comment] 2023-11-03 20:46
din't kn

**Comment by SonicTheHedgehog58987276** [comment] 2023-11-03 20:46
arn t

**Comment by SonicTheHedgehog58987276** [comment] 2023-11-03 20:47
proly aeny dupd it mlf

**Comment by SonicTheHedgehog58987276** [comment] 2023-11-03 20:49
w do i dlet his duat

**Comment by Thodor12** [comment] 2023-11-03 20:51
This cannot be deleted anymore, that's why I closed it, no big deal.

**Comment by SonicTheHedgehog58987276** [comment] 2023-11-03 20:52
o

**Comment by SonicTheHedgehog58987276** [comment] 2023-11-25 04:08
i now vandalized this duplicate of my issue
