### ISSUE TITLE
Allow the Post Box to keep items stocked.

### ISSUE THREAD

**Issue by truenachtara** [ldtteam/minecolonies-features#316] opened 2021-03-09 14:12 UTC
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my feature does not already exist.
- [x] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.643-ALPHA

## Is your feature request related to a problem?

Postboxes are simple, single active requests that get fulfilled once then cleared.

## Feature description

Just as the Warehouse and several other buildings have a "keep stocked" mode, the player's requesting tool should also have a "keep stocked" mode. It would be nice to do something like, have a stack of steak handy for yourself at any time.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment] 2021-03-09 16:46
Duplicate of #97

**Closed as completed by ravenbuilder934** 2021-03-09 16:46 UTC
Labels: Feature: Request
